- name: create Input Topic config map
  k8s_v1_config_map:
    name: api-topic
    namespace: '{{ namespace }}'
    labels:
      strimzi.io/kind: topic
      strimzi.io/cluster: my-cluster
    data:
      name: "gw.global.input.cloudevents"
      partitions: "1"
      replicas: "1"

- include_tasks: provision-http-src.yml 
- include_tasks: provision-kafka-src.yml
